manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: efogdev
      url-base: https://github.com/efogdev
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: "v0.3.0"
      import: app/west.yml
    - name: zmk-paw3395-driver
      remote: efogdev
      revision: "08f9a43"
    - name: zmk-pointer-2s-mixer
      remote: efogdev
      revision: "8f41b5e"
    - name: zmk-axis-clamper
      remote: efogdev
      revision: "637719f"
    - name: zmk-report-rate-limit
      remote: efogdev
      revision: "20e0742"
    - name: zmk-ec11-ish-driver
      remote: efogdev
      revision: "7b0828b"
    - name: zmk-auto-hold
      remote: efogdev
      revision: "8b11f48"
    - name: zmk-adaptive-feedback
      remote: efogdev
      revision: "82f83d1"
    - name: zmk-behavior-follower
      remote: efogdev
      revision: "c27fe57"
    - name: zmk-keymap-shell
      remote: efogdev
      revision: "b712a64"
    - name: zmk-acceleration-curves
      remote: efogdev
      revision: "14cbaa0"
    - name: zmk-input-processor-rotate-plane
      remote: efogdev
      revision: "86901be"
    - name: zmk-runtime-config
      remote: efogdev
      revision: "55fabb6"
    - name: zmk-bistable-behavior
      remote: efogdev
      revision: "652ae06"
    - name: zmk-ble-shell
      remote: efogdev
      revision: "45724d8"
    - name: zmk-esb-endpoint
      remote: efogdev
      revision: "cd4dd0e"
      submodules: true
    - name: zmk-feedback-common
      remote: efogdev
      revision: "92251ce"
    - name: zmk-shell-relay-core
      remote: efogdev
      revision: "b4a7eb0"
  self:
    path: config
